### ISSUE TITLE
Review and update access control

### ISSUE THREAD

**Issue by JeremyChiang** [steamclock/bluejay#10]
Right now in the middle of reorganizing our source code, there are times when it is not immediately clear what level of access certain code should have.

This is just an issue serving as a reminder to do a sanity check on our library's access control, and making sure we only expose what is critical.

Mainly just want to avoid giving developers too much access, especially to certain instance or static variables. Most accessible variables should probably be read only anyway, and I think a good API shouldn't require writing too much, or any, assignments.

**Comment by apike** [comment]
@JeremyChiang What's the status of this one?

**Comment by JeremyChiang** [comment]
Access control is in a decent state right now. We can file more specific issues when problems surface in the future.
