### ISSUE TITLE
Demo App:  Device Status wrongly displays "connected" after losing connection

### ISSUE THREAD

**Issue by abey** [steamclock/bluejay#111]
### Current Behaviour
The app says connected after losing Bluetooth connection with the peripheral. It defaults to "Connected" status even after manually clicking the disconnect button.

### Expected Behaviour
The connection status should automatically change to "disconnected" if the app loses Bluetooth connection with the peripheral. 

### Steps to recreate the bug
1. Open BlueJayDemo app and connect to a Bluetooth peripheral (for this example, I created a Heart Sensor using Lightblue)
2. Disconnect or disable Bluetooth of the peripheral. 
3. Open the device page and click disconnect and click "back" button
4. Go to the device page again and check the app status

**Comment by JeremyChiang** [comment]
Fixed.
