### ISSUE TITLE
Bluejay.isBluetoothAvailable should work prior to BlueJay.start

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#116]
Right now it traps prior to start, like many other methods, but it seems like in this case there is a clear answer if Bluejay isn't started (i.e. false), and being able to check that prior to start could simplify some code that depends on asynchronous events coming in that might need to touch the bluetooth state, i.e. you can put in a few judicious `guard bluejay.isBluetoothAvailable else { return }` and handle a lot of cases where bluejay either hasn't started or hasn't finished initialization yet

Another option would be to add an "isStarted" property for checking that, which would give you even more flexibility, but I think that's probable unnecessary in practice.

**Comment by JeremyChiang** [comment]
`hasStarted` boolean was already implemented. The improvement to `isBluetoothAvailable` is now also implemented in PR #175

**Comment by JeremyChiang** [comment]
Implemented.
