### ISSUE TITLE
Crash report: DiscoverService.swift:51

### ISSUE THREAD

**Issue by jacobminer** [steamclock/bluejay#122]
Crashed here in BSA: https://github.com/steamclock/bluejay/blob/master/Bluejay/Bluejay/DiscoverService.swift#L51

[desymcrash2.txt](https://github.com/steamclock/bluejay/files/1528089/desymcrash2.txt)

**Comment by nbrooke** [comment]
This was almost certainly fixed by one of the recent spate of stability fixes (#129, #130, #131)

**Comment by FIndustries** [comment]
I'm experiencing many crashes like this. I'm using version 0.6.3 of the library.

**Comment by nbrooke** [comment]
@FIndustries Can you please file a new bug and include a crash log, and any info you have about what you are doing when the crash occurs?
