### ISSUE TITLE
Crash report: Bluejay.swift:816

### ISSUE THREAD

**Issue by jacobminer** [steamclock/bluejay#123]
Crashed here (in BSA): https://github.com/steamclock/bluejay/blob/master/Bluejay/Bluejay/Bluejay.swift#L816

[desymcrash1.txt](https://github.com/steamclock/bluejay/files/1528093/desymcrash1.txt)

**Comment by nbrooke** [comment]
This was almost certainly fixed by one of the recent spate of stability fixes (#129, #130, #131)
