### ISSUE TITLE
Can't call disconnect and connect back to back

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#132]
Right now, if you call disconnect and then immediately call connect, the connect will fail, because you are still technically connected to the original device when the connect is issued, so it runs afoul of the double connect protection. 

Even calling it from the completion callback of disconnect doesn't work, because the completion callback happens before the internal `connectedPeripheral` is cleared. I could also see this causing other problems (anything that triggered from the disconnection callback that checked if anything is connected would get the wrong answer).

Allowing this possibility can be useful for some scanning oriented apps. The case I encountered it, I was doing a discovery, stopping scan to connect to the device to read some data to display disconnecting and then (usually) starting the scan again. However in some cases, the new data would trigger a separate operation that needed to connect to the device again to take some actions, but that second connect would always fail because the disconnect had never completed before it was called. Refactoring the code to detect this and maintain the connection is possible, but annoying in my case. The workaround I need using was to trigger the event from a main thread async dispatch inside the disconnect callback, which delayed it enough that it would always work.

I propose a two part fix:
- Allow enqueuing a connection when we are already connected if the is a disconnection in the queue.
- Clear `connectingPeripheral` and `connectedPeripheral` before doing the disconnection complete callback (not technically needed to fix this if we have the first item, but still cleaner overall I think).

**Comment by JeremyChiang** [comment]
Implemented.
