### ISSUE TITLE
Allow some better strategy then trapping for resolving multiple listens.

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#141]
Setting up multiple listens is a programmer error, but it's a little bit of a painful one to spot in all cases, and often an individual app that is likely to run afoul of it DOES have a clear strategy that you can use for resolving them (for example, latest listen goes ahead and the previous one is sent and error and cancelled).

I think we should add a configuration var the Bluejay that specifies a behaviour to use on double listens, which could be (for now) one of "trap" (current behaviour), "oldestWins" and "newestWins", which should all be pretty easy to implement. We could also add "allowBoth" at some point, that that is much more complicated, and I think a little questionable from a design standpoint.

**Comment by JeremyChiang** [comment]
Implemented.
