### ISSUE TITLE
ListenRestorer delegate is not getting called

### ISSUE THREAD

**Issue by shekhar-suman** [steamclock/bluejay#143]
https://github.com/steamclock/bluejay/blob/d95e58f7b233c1090ee5f17b1a7f7a69f94a9a34/Bluejay/Bluejay/Bluejay.swift#L812

listenCaches stores restorers using restoration id as key. But you are accessing it by using Bluejay instance uuid hence it always returns nil.

```
private func requestListenRestoration() throws {
        log("Starting listen restoration.")
        
        guard
            let listenCaches = UserDefaults.standard.dictionary(forKey: Constant.listenCaches),
            // let cacheData = listenCaches[uuid.uuidString] as? [Data]
            let cacheData = listenCaches[restoreIdentifier!] as? [Data]
        else {
            log("No listens to restore.")
            return
        }
```

https://github.com/steamclock/bluejay/blob/d95e58f7b233c1090ee5f17b1a7f7a69f94a9a34/Bluejay/Bluejay/Peripheral.swift#L307

**Comment by JeremyChiang** [comment]
This should now be fixed with the release of v0.5.1 🎉
