### ISSUE TITLE
cancelEverything might not properly clean up internal state

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#151]
I had some code that was using `cancelEverything` in a situation where `disconnect` would be fine, I switched it to disconnect, but saw two strange piece of behaviour I think were related to using `cancelEverything`

One is that when using cancel everything, it would disconnect, but then would auto-reconnect to the device (which makes sense given the code, it seems to not clear the auto reconnect flag, which I feel like it should).

The other (vaguer) issue is that i saw an incorrect event in queue error (didn't note down the details carefully enough when it happened, so can't say exactly what) soon after one of the cancelAnything calls. I'm less clear on how that happened, but it seems possible that with an immediate disconnect like that, there could be situations where the response from the first item in the queue that is cancelled still gets delivered after the queue has been cleared. 

Seems like making `cancelEverything` not a public function, or changing the semantics (maybe with a  rename) so that it does not actually disconnect might also be reasonable solutions if it's hard to make it behave like you would expect (clear the queue + clean disconnect).

**Comment by JeremyChiang** [comment]
The `autoReconnect` on `cancelEverything` also caused some problems in another project I'm working on. I've improved it slightly by adding an extra parameter to `cancelEverything`:

```
public func cancelEverything(_ error: Error? = nil, autoReconnect: Bool? = nil) {
    if let autoReconnect = autoReconnect {
        shouldAutoReconnect = autoReconnect
    }
    ...
```

**Comment by JeremyChiang** [comment]
The similar but different requirements and behaviours between `cancelEverything` and `disconnect`, as well as different modes to perform them have been cleared and cleaned up in v0.7.0.

You can now cancel everything with or without disconnecting, disconnect either immediately or queued, and the queue will propagate all events and iterate through all operations accordingly.

Closing this for now, as we can discuss any remaining issues in #170.
