### ISSUE TITLE
Need support in Serialisation and Deserialization 

### ISSUE THREAD

**Issue by iNicson** [steamclock/bluejay#153]
Hi, You guys have done a wonderful contribution to BLE coding using swift,  
Well I need some support in advanced serialization and deserialization with bluejay as it is not documented anywhere,

eg. The Read Responses

word count of items [ repeated
word wItemNum
dword dwItemTime ]

also 

typedef union tItemStatsTag
{
  struct
 {
 // little endian, so lower byte is stored first
 byte bYesterday_percentage;
byte bToday_percentage;
byte bTomorrow_percentage;
  byte bUnused;
} sStats;
   } tItemStatsTag; 

Please do the same as writable models also , so I can have a better understanding on how to use this framework  in real time projects

**Comment by JeremyChiang** [comment]
https://github.com/steamclock/bluejay#deserialization-and-serialization
