### ISSUE TITLE
State restoration and connect callbacks don't play well together.

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#156]
If you are using both state restoration and calling connect with a non-trivial callback, it's easy to end up in various strange situations. I'm not even totally convinced that there are bugs here, it's mainly just that it's easy to do the wrong thing without Bluejay warning you in any way.

The issue is that if you are doing work in connect callbacks, it's easy to wind up in a situation where those don't get called, without realizing what has happened. Calls to connect during state restoration are ignored silently in favour of using the connect that is triggered by state restoration itself.

The correct fix as it stands now, is to make sure you can correctly handle the situation where you get a connect that you didn't request, via installing a global ConnectionObserver and NOT calling connect yourself on startup if there is already a connect in progress, however, this approach isn't perfect either, because if you have an app with some more complicated connect usage (for example, connecting at two different times to do two different things, which the app I encountered this in does), you may need some gnarly tracking of state to know what the correct response to a given connect is.

At the very least, even if there isn't a bug here, and the right thing is to just do what I ended up doing and make sure there is always a ConnectionObserver to catch any connects coming from restoration , I think that there should be some warnings around this to try and point people to the right path.

I think the most straightforward fix is to ditch the silent ignoring of duplicate connects during restoration, and make that an error. Then it forces clients to realize that they can't just call connect on every startup, but need to handle starting up in the consenting state separately. Some other more sophisticated options might be to make multiple connects behave correctly (both callbacks get called). Or to have some connect equivalent of listen restoration, where you are required to specify a callback to process a connect that happens from a restoration.

**Comment by JeremyChiang** [comment]
Implemented.
