### ISSUE TITLE
Crash when trying to disconnect and immediately connect to another device

### ISSUE THREAD

**Issue by akmarinov** [steamclock/bluejay#168]
So I have two devices, i connect to one, then try to disconnect and in the completion connect to the next device.

```
bluejay.disconnect { result in
          bluejay.connect(discovery.peripheralIdentifier, timeout: Timeout.seconds(30)) { (result) in
            switch result {
            case .success:
                self.connectedPeripheral = discovery
                completion(true)
            default:
                self.startRefreshTimer()
                completion(false)
            }
        }
}
```

I get a crash when trying to force unwrap the `connectedPeripheral` here

![screenshot 2018-08-30 18 13 33](https://user-images.githubusercontent.com/1358638/44861538-63cdf200-ac81-11e8-9d89-592996340585.png)

It seems that the disconnect completion closure gets return before the `disconnectCleanUp` closure gets called, which sets the connecting peripheral to nil.

The disconnect closure should return after all the disconnect work has been completed and optionals shouldn't be force unwrapped.

**Comment by JeremyChiang** [comment]
This is related and discussed in https://github.com/steamclock/bluejay/pull/167 as well. When reviewing that issue, I also felt like we need to move the for-loop that notifies all observers - however, as mentioned in that PR, I want to get some more opinions, feedbacks, and verifications before trying that out.

**Comment by JeremyChiang** [comment]
For connecting to a different device, this should now work (in v0.7.0) without requiring any delays assuming the second device is already ready to accept a new connection.
