### ISSUE TITLE
Should be a more obvious way to cancel connect attempts

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#169]
Disconnect looks promising for that, but only disconnects when connected, which is probably not what people are expecting. Right now the only way to cancel an in flight connection is to use cancelEverything(allowReconnect: false), which is slightly non-intuitive.

It's also probably less safe to cancelEverything then using disconnect that cancels connect attempts. cancelEverything doesn't do as much sanity checking so you won't get an error if you aren't actually trying to connect, which would be nice from a consistency standpoint. Also disconnect should automatically suppress reconnection, which you need to know to do on cancelEverything.

An alternative would be to add a stopConnection (or similarly named function) that ONLY stops an in-flight but not completed connection attempt, similar to how we have stopScanning to cancel a scan. This would be slightly more consistent, but is maybe not as obvious as disconnect just doing that.

**Comment by kylebrowning** [comment]
👍 

(Also, hey @nbrooke)

**Comment by JeremyChiang** [comment]
#170 now addresses all of these issues:
1) You can now disconnect both a connecting or connected peripheral
2) You can either queue the disconnect or force an immediate disconnect
3) You can cancel everything with or without disconnect
4) Calling both disconnect or cancelEverything (with disconnect enabled) will disable auto-reconnect
5) There is also now a better way to control auto-reconnect through a `DisconnectHandler`
6) Order of operations and callbacks in the queue is also cleaned up for all disconnection reasons

Closing this for now, as we can discuss any remaining issues or concerns in #170.
