### ISSUE TITLE
There's no way to disable throttling discoveries with similar RSSI

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/bluejay#171]
Ran into this problem on an internal project. 

There's currently a somewhat arbitrary limit in `scan` where discoveries of the same device with RSSI less than 5dBm from the last discovery aren't reported. While I think it makes sense to have some sort of mechanism for doing this here, it would be nice to be able to change what the threshold is, or disable it completely.

**Comment by JeremyChiang** [comment]
Released in v0.6.5
