### ISSUE TITLE
Carthage issue - @rpath/ObjcExceptionBridging.framework/ObjcExceptionBridging

### ISSUE THREAD

**Issue by DrAma999** [steamclock/bluejay#189]
Summary:
Added bluejay by using carthage as usual, once I launch the app I get:

> dyld: Library not loaded: @rpath/ObjcExceptionBridging.framework/ObjcExceptionBridging
>   Referenced from: /private/var/containers/Bundle/Application/51CD4F13-FF64-46B4-909D-4D43635291D0/Glorious.app/Frameworks/Bluejay.framework/Bluejay
>   Reason: image not found

While reading issues I've found that could be related to [XCGLogger](https://github.com/DaveWoodCom/XCGLogger/issues/205)  that seems to be recently added to the library as a dependency

Steps to Reproduce:

1.  Add Bluejay as dependency in your Cartfile
2.  Launch the command `carthage update --platform iOS`
3.  Drag and drop the framework in Linked Frameworks and Library
4. Add in build phase the copy frameworks script
5. Build and run on device

Actual Result:
Crash due to:
> dyld: Library not loaded: @rpath/ObjcExceptionBridging.framework/ObjcExceptionBridging
>   Referenced from: /private/var/containers/Bundle/Application/51CD4F13-FF64-46B4-909D-4D43635291D0/Glorious.app/Frameworks/Bluejay.framework/Bluejay
>   Reason: image not found

Expected Result: 
Import library correctly

Device, Build, OS:
iPhone X, 12.1, iOS

**Comment by JeremyChiang** [comment]
Good catch, thank you. I definitely missed this, and will update the library now.

**Comment by JeremyChiang** [comment]
Fixed and released.
