### ISSUE TITLE
Accessory that request a password at connect

### ISSUE THREAD

**Issue by soufianeEssabbane** [steamclock/bluejay#197]
Summary:

Hi, while trying to connect to an accessory that requires a password, a popup shows and dismiss rapidly, without even having time to write the password. how can we handle this kind of connexions ?
like making at least the popup wait the time needed to write the password ? or how can we write the password programatically during bluejay.connect ? 

Steps to Reproduce:

1. scan for accessory 
2. selected accessory 
3. make bluejay.connect ...

Actual Result:
a natif popup for password displays and dismiss rapidly.

Expected Result: 
send accessory password programmatically or make natif popup password wait

Device, Build, OS:
iOS

**Comment by JeremyChiang** [comment]
Hi @soufianeEssabbane, it sounds like you have some UI bugs unrelated to Bluejay. There's no code in Bluejay that can show or dismiss an alert controller. I would suggest finding code that dismisses (or could potentially dismiss) alerts your app and trace back from there to see what is causing the alert to disappear unexpectedly.

**Comment by JeremyChiang** [comment]
Hi @soufianeEssabbane did you make any progress on resolving this issue? Let me know. Otherwise, I will be closing this issue soon for inactivity. Thanks.

**Comment by soufianeEssabbane** [comment]
Hi @JeremyChiang sometimes for some BLE devices some characteristics are protected with a password, when you try to subscribe to notification from a characteristic or read a protected one, the OS expose to you a native Popup for password.
but when you read or subscribe to many protected characteristics you should wait for the user to write the password that popups for the first charateristic before continuing reading the rest ... otherwise the popup will be dismissed.
