### ISSUE TITLE
Bluejay can crash when a device is unpaired (Bluejay.swift: 1437)

### ISSUE THREAD

**Issue by kylebrowning** [steamclock/bluejay#198]
Summary: Forgetting a device in iOS settings, while attempting to connect causes a crash.

Steps to Reproduce:

1. Request a get or write an encrypted attribute to get a pairing
2. Pair with the device.
3. Turn off device so that it disconnects unexpectedly and Bluejay attempts to reconnect
4. Forget device in iOS BLE Settings

Actual Result: App crashes on line 1437 in Bluejay.swift

```swift
guard let connectingError = connectingError else {
                        preconditionFailure("Missing connecting error at the end of a disconnect clean up after cancelling a pending connection.")
                    }
```

Expected Result: 
App should not crash

Device, Build, OS:
iPhone XS Max, iOS 12.1, Bluejay (0.8.1) `b01d53f0592cc1cf26382d8df1734c16e83286e4`

**Comment by JeremyChiang** [comment]
Also thanks for filing this. I need to look into this more, but initial investigation suggests that we might need to figure what CoreBluetooth does when a device is unpaired, and assign the correct error to `connectingError` before this check occurs.

**Comment by FIndustries** [comment]
I have the same problem just disabling the bluetooth from the control center. It crashes a lot of times but not every time.

**Comment by apike** [comment]
Let's try and get a fix for this into a point release, rather than holding to the next scheduled update.

**Comment by kylebrowning** [comment]
@apike It'd be nice to get this in too, https://github.com/steamclock/bluejay/pull/200

But I'd understand fi that needs a more scheduled update.
