### ISSUE TITLE
XCGLogger crash

### ISSUE THREAD

**Issue by LeeCenY** [steamclock/bluejay#209]
Summary:

Steps to Reproduce:

1. Continuously sending data to crash   for i in 0..<10000
2. 
3. 

Actual Result: XCGLogger crash

Expected Result: no  crash

Device, Build, OS:  iPhone 8 iOS 12.3.1

![WX20190615-190129](https://user-images.githubusercontent.com/9047094/59550868-094d1a80-8fa3-11e9-8640-4a2729929d16.png)
![WX20190615-190159](https://user-images.githubusercontent.com/9047094/59550869-0baf7480-8fa3-11e9-987f-a91e5029a284.png)

**Comment by JeremyChiang** [comment]
Sorry what?

Maybe https://github.com/DaveWoodCom/XCGLogger can help?
