### ISSUE TITLE
Update Bluejay and Dittojay to latest Swift and Xcode

### ISSUE THREAD

**Issue by JeremyChiang** [steamclock/bluejay#223]

**Comment by eminisrafil** [comment]
Hey guys, thanks for creating and managing this project. Any update on this? Thanks!

**Comment by JeremyChiang** [comment]
Thanks for checking in. PR for this is up and a new version will be released in the next few days.

**Comment by JeremyChiang** [comment]
@eminisrafil sorry for the wait. Bluejay v0.8.6 is released just now. Let me know if there's any Xcode or build related problems. I will be doing some more testing today as well.
