### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by apike** [steamclock/bluejay#4]

**Comment by TofPlay** [comment]
Hi,
For iOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by apike** [comment]
@TofPlay Thanks for the suggestion - we'd like to add Carthage too. We don't use Carthage internally, so we can ping you to double-check it once we have it hooked up. :)

**Comment by JeremyChiang** [comment]
@TofPlay and @apike, Bluejay is compatible with Carthage and the README has been updated. It should work on iOS, and we have plans to test Bluejay on watchOS and tvOS as they will be getting Core Bluetooth support in iOS 11.

**Comment by TofPlay** [comment]
@JeremyChiang excellent 👍 🙂
For watchOS and tvOS you can take a look to [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 😉
