### ISSUE TITLE
Improve auto reconnect

### ISSUE THREAD

**Issue by JeremyChiang** [steamclock/bluejay#77]
Auto reconnect is a nice feature to have to recover from unexpected disconnection, but some apps require quite a bit of setup every time a connection is established. For example, some apps need to authenticate with the Bluetooth module they use on their chip on every new connection.

Perhaps it would be nice if there is a way to provide a block that can be used by every auto reconnect attempt.

**Comment by Hans92** [comment]
Also setting the auto reconnect trial count would help a lot.

**Comment by JeremyChiang** [comment]
Added in PR #170
