### ISSUE TITLE
Support write without response

### ISSUE THREAD

**Issue by JeremyChiang** [steamclock/bluejay#79]
Because we haven't worked with clients that need write without response, Bluejay doesn't currently support this at all. This is probably pretty important to support though.

**Comment by avtr** [comment]
I suggest to add `type: CBCharacteristicWriteType` parameter to `write` methods in classes (`Bluejay` and `Peripheral`) and property to `WriteCharacteristic`.

**Comment by JeremyChiang** [comment]
Implemented and merged.
