### ISSUE TITLE
Bluetooth mocking and simulation app for automated and manual testing

### ISSUE THREAD

**Issue by apike** [steamclock/bluejay#8]
This is surprisingly complicated and gnarly to do, but would be a valuable thing both for maintaining Bluejay and our various Bluetooth apps. Ideally we could simulate specific cases such as backgrounding, communication failures, and so on. These are challenging to mock and simulate because they depend on measuring and reproducing what iOS is doing in various edge cases.

In addition to being helpful for automated testing, mocking would allow folks to do basic testing in the simulator, which would be quite helpful.

**Comment by JeremyChiang** [comment]
We have started breaking out specific tasks.
