### ISSUE TITLE
Suggestion to add SwiftLint

### ISSUE THREAD

**Issue by larryonoff** [steamclock/bluejay#94]
I have a suggestion on adding swiftlint into the project. I can create PR if community doesn't have any doubts about this.

Please feel free on changing configuration that I provided below.

```
included:
  - TBD
excluded:
  - Carthage
  - Pods

disabled_rules:
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - large_tuple
  - nesting
  - redundant_optional_initialization
  - type_body_length
  - type_name
  - variable_name
  - weak_delegate

closing_brace: error
comma: error
colon: error
empty_count: warning
function_body_length:
  warning: 100
  error: 150
opening_brace: error
return_arrow_whitespace: error
statement_position: error
todo: warning
trailing_semicolon: error

```

**Comment by JeremyChiang** [comment]
I've not used SwiftLint before, but realm seems to have a great and smart team. I love their NSPredicate cheat sheet. If this is one of the best linters out there for Swift and is used by other major libraries, I'm down to adopt this.

**Comment by larryonoff** [comment]
@JeremyChiang I think `SwiftLint` is the most mature linter for Swift. There's not official linter from Swift team, but Realm did a very good job by implementing open-source `SwiftLint`. Other iOS devs that I know use `SwiftLint`.

I'll create PR over the week-end.

**Comment by larryonoff** [comment]
example of framework that uses SwiftLint: https://github.com/Moya/Moya

**Comment by larryonoff** [comment]
Hopefully will start working on this issue these weekend.
