### ISSUE TITLE
Investigate switching to a custom error type

### ISSUE THREAD

**Issue by nbrooke** [steamclock/bluejay#95]
Noted in the discussion on #93 that all errors are NSErrors right now. I believe there was a good reason for this in the original Swift 2 code, but there have been several changes to the Swift error system since then. In particular the addition of the LocalizedError protocol, so you can get a message back from something that you don't know if is a custom error or an NSError (since the code also deals with some CoreBluetooth NSErrors) in a  clean way. 

It's worth looking into if we can easily replace the current hand built NSErrors with a custom error enum now.

**Comment by larryonoff** [comment]
Created PR #97. Please review.
